export default {
    eventInputData: [
        {
            "Event name": "Impact Hackathon",
            "Country": "Norway",
            "City": "Oslo",
            "Start Date": "21.09.2018",
            "Event type": "hackathon",
            "Pre-event": "no",
            "Funding source": "semi-gov",
            "N of participants registered": 77,
            "N of participants attended": 55,
            "N of idea pitched": 20,
            "N teams end": 7,
            "N of mentors": 8,
            "Gender: females": 12,
            "Gender: males": 43,
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Tech for Agriculture",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "08.06.2018",
            "Event type": "hackathon",
            "Pre-event": "yes",
            "Funding source": "gov",
            "N of participants registered": 109,
            "N of participants attended": 95,
            "N of idea pitched": 15,
            "N teams end": 9,
            "N of mentors": 13,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Visual",
            "Country": "Belarus",
            "City": "Minsk",
            "Start Date": "08.06.2018",
            "Event type": "hackathon",
            "Pre-event": "",
            "Funding source": "",
            "N of participants registered": "",
            "N of participants attended": 130,
            "N of idea pitched": 27,
            "N teams end": 15,
            "N of mentors": 17,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": 2,
            "N teams funded": ""
        },
        {
            "Event name": "SpaceTech",
            "Country": "Latvia",
            "City": "Riga",
            "Start Date": "11.05.2018",
            "Event type": "hackathon",
            "Pre-event": "",
            "Funding source": "",
            "N of participants registered": 74,
            "N of participants attended": "",
            "N of idea pitched": 16,
            "N teams end": 9,
            "N of mentors": 13,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Wellbeing vol 2",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "04.05.2018",
            "Event type": "hackathon",
            "Pre-event": "yes",
            "Funding source": "gov",
            "N of participants registered": 91,
            "N of participants attended": 70,
            "N of idea pitched": 12,
            "N teams end": 7,
            "N of mentors": 8,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": 1,
            "N teams funded": ""
        },
        {
            "Event name": "Chisinau",
            "Country": "Moldova",
            "City": "Chisinau",
            "Start Date": "27.04.2018",
            "Event type": "hackathon",
            "Pre-event": "",
            "Funding source": "gov",
            "N of participants registered": 112,
            "N of participants attended": 70,
            "N of idea pitched": 12,
            "N teams end": 10,
            "N of mentors": 10,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Cyber Security",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "22.04.2018",
            "Event type": "hackathon",
            "Pre-event": "yes",
            "Funding source": "",
            "N of participants registered": 92,
            "N of participants attended": 85,
            "N of idea pitched": 19,
            "N teams end": 8,
            "N of mentors": 9,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": 2,
            "N teams funded": ""
        },
        {
            "Event name": "Digital Construction",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "06.08.2018",
            "Event type": "hackathon",
            "Pre-event": "yes",
            "Funding source": "private",
            "N of participants registered": 109,
            "N of participants attended": 85,
            "N of idea pitched": 22,
            "N teams end": 10,
            "N of mentors": 14,
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Idea Garage Cyber Security Tallinn Powered by UK",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "28.03.2018",
            "Event type": "idea garage",
            "Pre-event": "",
            "Funding source": "",
            "N of participants registered": 45,
            "N of participants attended": "",
            "N of idea pitched": "",
            "N teams end": "",
            "N of mentors": "",
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": 1,
            "N teams funded": ""
        },
        {
            "Event name": "Women in Tech",
            "Country": "Ukraine",
            "City": "Lviv",
            "Start Date": "16.03.2018",
            "Event type": "hackathon",
            "Pre-event": "",
            "Funding source": "gov",
            "N of participants registered": "",
            "N of participants attended": 95,
            "N of idea pitched": 22,
            "N teams end": 19,
            "N of mentors": "",
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Idea Garage Workability",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "08.03.2018",
            "Event type": "idea garage",
            "Pre-event": "",
            "Funding source": "private",
            "N of participants registered": 82,
            "N of participants attended": 65,
            "N of idea pitched": 10,
            "N teams end": 8,
            "N of mentors": "",
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": 1,
            "N teams funded": ""
        },
        {
            "Event name": "Hardware and Arts",
            "Country": "Latvia",
            "City": "Riga",
            "Start Date": "02.03.2018",
            "Event type": "hackathon",
            "Pre-event": "",
            "Funding source": "gov",
            "N of participants registered": 108,
            "N of participants attended": 90,
            "N of idea pitched": 32,
            "N teams end": 16,
            "N of mentors": "",
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Edtech",
            "Country": "Moldova",
            "City": "Chisinau",
            "Start Date": "23.02.2018",
            "Event type": "hackathon",
            "Pre-event": "",
            "Funding source": "private",
            "N of participants registered": 91,
            "N of participants attended": 30,
            "N of idea pitched": 11,
            "N teams end": 6,
            "N of mentors": "",
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": 1,
            "N teams funded": ""
        },
        {
            "Event name": "Idea Garage: Cyber Security Latvia",
            "Country": "Latvia",
            "City": "Riga",
            "Start Date": "16.02.2018",
            "Event type": "idea garage",
            "Pre-event": "no",
            "Funding source": "private",
            "N of participants registered": 53,
            "N of participants attended": 14,
            "N of idea pitched": 6,
            "N teams end": 3,
            "N of mentors": 6,
            "Gender: females": 5,
            "Gender: males": 7,
            "N of teams alive 6 months after the event": 0,
            "N teams funded": 0
        },
        {
            "Event name": "Baltic Open Banking",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "16.02.2018",
            "Event type": "hackathon",
            "Pre-event": "yes",
            "Funding source": "private",
            "N of participants registered": 137,
            "N of participants attended": "",
            "N of idea pitched": 33,
            "N teams end": 15,
            "N of mentors": "",
            "Gender: females": "",
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        },
        {
            "Event name": "Idea Garage: Cyber Security Vilnius",
            "Country": "Lithuania",
            "City": "Vilnius",
            "Start Date": "23.01.2018",
            "Event type": "idea garage",
            "Pre-event": "no",
            "Funding source": "private",
            "N of participants registered": 58,
            "N of participants attended": 45,
            "N of idea pitched": 10,
            "N teams end": 5,
            "N of mentors": 7,
            "Gender: females": 20,
            "Gender: males": 25,
            "N of teams alive 6 months after the event": 1,
            "N teams funded": 0
        },
        {
            "Event name": "Abhasia project: 2nd event",
            "Country": "Georgia",
            "City": "",
            "Start Date": "",
            "Event type": "idea garage",
            "Pre-event": "no",
            "Funding source": "private",
            "N of participants registered": 80,
            "N of participants attended": 50,
            "N of idea pitched": 12,
            "N teams end": 6,
            "N of mentors": 3,
            "Gender: females": 15,
            "Gender: males": 35,
            "N of teams alive 6 months after the event": 0,
            "N teams funded": 0
        },
        {
            "Event name": "Idea Garage: Cyber Security Tallinn",
            "Country": "Estonia",
            "City": "Tallinn",
            "Start Date": "28.03.2018",
            "Event type": "idea garage",
            "Pre-event": "no",
            "Funding source": "private",
            "N of participants registered": 45,
            "N of participants attended": 30,
            "N of idea pitched": "",
            "N teams end": "",
            "N of mentors": 8,
            "Gender: females": 27,
            "Gender: males": "",
            "N of teams alive 6 months after the event": "",
            "N teams funded": ""
        }
    ],
    KPIModels: [],
    mappingDefinitions: [],
};